#!/bin/bash

# load settings
. /etc/vidaas/bootstrap-settings
. /etc/vidaas/system-settings

# load environment
. /etc/vidaas/env

#defaults
monitor_git=/root/git/

# as recommended http://rhq-project.org/display/RHQ/Building+RHQ
export MAVEN_OPTS="-Xms256M -Xmx1024M -XX:PermSize=128M -XX:MaxPermSize=256M"

# packages to install for monitoring node
projectnode_packages="maven2 git less vim unzip postgresql apache2 libapache2-mod-jk daemontools pwgen"

# install openjdk
source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/openjdk.sh

echo "Installing project node packages $projectnode_packages"
if ! DEBIAN_FRONTEND=noninteractive apt-get -qqy install $projectnode_packages ; then
  echo "failed to install required packages"
  exit 1
fi

# Create postgres database for RHQ
source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/postgres-createrole.sh rhqadmin rhq
# Database used during maven build
source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/postgres-createrole.sh rhqadmindev rhqdev
source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/postgres-createrole.sh rhqadmintest rhqtest

if ! [ -d $monitor_git ] ; then
  mkdir -p $monitor_git
  if cd $monitor_git && git clone git://git.fedorahosted.org/git/rhq/rhq.git ; then
    echo "git clone complete"
  else
    echo "git clone failed" ; exit 1
  fi
fi
if cd $monitor_git/rhq && git pull ; then
  source $vidaas_admin_repo_path/admin/$vidaas_branch/services/rhq/settings.xml.sh > ~/settings.xml
  if cd $monitor_git/rhq/ && mvn -Penterprise,dist,prod -Ddbsetup -Dmaven.test.skip=true -s ~/settings.xml install ; then
    echo "build complete"
  else
    echo "RHQ build failed" ; exit 1
  fi
else
  echo "git clone failed" ; exit 1
fi

echo "Building RHQ..."

  echo "RHQ build failed" ; exit 1
fi

echo "Monitoring node install complete"
