#!/bin/bash

# load settings
. /etc/vidaas/bootstrap-settings
. /etc/vidaas/system-settings

# load environment
. /etc/vidaas/env

# packages to install for monitoring node
projectnode_packages="maven2 git less vim unzip postgresql apache2 libapache2-mod-jk daemontools pwgen"

# install openjdk
source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/openjdk.sh

echo "Installing project node packages $projectnode_packages"
if ! DEBIAN_FRONTEND=noninteractive apt-get -qqy install $projectnode_packages ; then
  echo "failed to install required packages"
  exit 1
fi

# Create postgres database for RHQ
source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/postgres-createrole.sh rhquser rhqdb

echo "Monitoring node install complete"
