#!/bin/bash

source /etc/vidaas/settings

default_packages=vim apticron openssh-server

echo "Unattended update/upgrade of minimal image..."
if apt-get -qq update ; then
  if ! apt-get -qqy upgrade ; then
    echo "upgrade failed"
    exit 1
  fi
else
  echo "update failed"
  exit 1
fi

echo "Installing default packages..."
if ! apt-get -qqy install $default_packages
  echo "install of default packages failed"
  exit 1
fi

source $vidaas_config_repo_path/admin/scripts/vidaas-$(vidaas_node_type)node-install
