#!/bin/bash

# find out if VMware tools are working
if [ -e /etc/init.d/vmware-tools ] ; then
  if ! /etc/init.d/vmware-tools status ; then
    install_tools=yes
  fi
else
  install_tools=yes
fi

# get admin repository
cd
if ! svn checkout https://vidaas.googlecode.com/svn/admin ; then
  echo "svn checkout failed"
  exit 1
fi

# install tools
if [ -n "$install_tools" ] ; then
  apt-get install linux-headers-2.6-amd64 make
  cd
  if ! tar -xzf admin/bin/VMwareTools-8.6.0-425873.tar.gz ; then
    echo "unable to extract VMwareTools"
    exit 1
  fi
  perl ./vmware-tools-distrib/vmware-install.pl -d
  rm -r vmware-tools-distrib
else
  echo "VMware tools already installed and running"
fi

# not essential (and noisy)
apt-get -y remove mpt-status

