#!/bin/sh

if [ "x$1" = "xprecustomization" ]; then
  exit 0
fi

exec 2>&1 >> /var/log/customization.log
echo "Customization started `date`"

#put your customization settings here
vidaas_admin_repo_path=/root/svn/
vidaas_node_type=project

#existing settings file overrides defaults
if [ -f /etc/vidaas/settings ] ; then
  . /etc/vidaas/settings
fi
if [ ! -d /etc/vidaas ] ; then
  mkdir /etc/vidaas
fi
echo "Updating settings file..."
(
cat <<EndOfFile
vidaas_admin_repo_path=$vidaas_admin_repo_path
vidaas_node_type=$vidaas_node_type
EndOfFile
) > /etc/vidaas/settings

echo "Checking out admin repository into $vidaas_config_repo_path"
if [ ! -f /usr/bin/svn ] ; then
  if ! apt-get -qqy install subversion ; then
    echo "Unable to install subversion package"
    exit 1
  fi
fi
mkdir -p $vidaas_admin_repo_path 2> /dev/null
if ! cd $vidaas_admin_repo_path ; then
  echo "repository path $vidaas_admin_repo_path invalid"
  exit 1
fi
if ! svn checkout https://vidaas.googlecode.com/svn/admin ; then
  echo "svn checkout failed"
  exit 1
fi

# run vidaas install
$vidaas_admin_repo_path/admin/scripts/vidaas-install
