#!/bin/sh

# type of node to build
vidaas_node_type=project

# svn branch for code and configuration files
vidaas_branch=trunk

# install shibboleth (true/false)
vidaas_shib=false q

### it's usually not required to touch any of the options below

#put your customization settings here
vidaas_admin_repo_path=/root/svn/