#!/bin/sh

# type of node to build
vidaas_node_type=project

# svn branch for code and configuration files
vidaas_branch=branches/WithRoles

# revision of vidaas code (default HEAD)
vidaas_source_revision=600

# install shibboleth (true/false)
vidaas_shib=false

# local user for debug purposes
debug_user=dave
