package uk.ac.ox.oucs.vidaas.entity;

// Generated 01-Aug-2011 14:49:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserProjectId generated by hbm2java
 */
@Embeddable
public class UserProjectId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3193427657511934251L;
	private int projectId;
	private int userId;

	public UserProjectId() {
	}

	public UserProjectId(int projectId, int userId) {
		this.projectId = projectId;
		this.userId = userId;
	}

	@Column(name = "Project_ID", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "User_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserProjectId))
			return false;
		UserProjectId castOther = (UserProjectId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
