package uk.ac.ox.oucs.vidaas.entity;

// Generated 01-Aug-2011 14:49:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserDatabaseId generated by hbm2java
 */
@Embeddable
public class UserDatabaseId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9116343676018509732L;
	private int databaseId;
	private int userId;

	public UserDatabaseId() {
	}

	public UserDatabaseId(int databaseId, int userId) {
		this.databaseId = databaseId;
		this.userId = userId;
	}

	@Column(name = "Database_ID", nullable = false)
	public int getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(int databaseId) {
		this.databaseId = databaseId;
	}

	@Column(name = "User_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserDatabaseId))
			return false;
		UserDatabaseId castOther = (UserDatabaseId) other;

		return (this.getDatabaseId() == castOther.getDatabaseId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDatabaseId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
