package uk.ac.ox.oucs.vidaas.entity;

// Generated 01-Aug-2011 14:49:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;

/**
 * WebApplication generated by hbm2java
 */
@Entity
@Table(name = "web_application", catalog = "vidaas_v3")
@NamedQueries({
    @NamedQuery(name = "WebApplication.findAll", query = "SELECT w FROM WebApplication w"),
    @NamedQuery(name = "WebApplication.findByWebID", query = "SELECT w FROM WebApplication w WHERE w.webId = :webID"),
    @NamedQuery(name = "WebApplication.findByUrl", query = "SELECT w FROM WebApplication w WHERE w.url = :url"),
    @NamedQuery(name = "WebApplication.findByVersion", query = "SELECT w FROM WebApplication w WHERE w.version = :version")})
public class WebApplication implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8331042948630374311L;
	private Integer webId;
	private Integer version;
	private String url;
	private Set<ProjectDatabase> projectDatabases = new HashSet<ProjectDatabase>(
			0);

	public WebApplication() {
	}

	public WebApplication(String url, Set<ProjectDatabase> projectDatabases) {
		this.url = url;
		this.projectDatabases = projectDatabases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Web_ID", unique = true, nullable = false)
	public Integer getWebId() {
		return this.webId;
	}

	public void setWebId(Integer webId) {
		this.webId = webId;
	}

	@Version
	@Column(name = "Version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "URL", length = 145)
	@Length(max = 145)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "webApplication")
	public Set<ProjectDatabase> getProjectDatabases() {
		return this.projectDatabases;
	}

	public void setProjectDatabases(Set<ProjectDatabase> projectDatabases) {
		this.projectDatabases = projectDatabases;
	}

}
