package uk.ac.ox.oucs.vidaas.entity;

// Generated 01-Aug-2011 14:49:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SchemaLogId generated by hbm2java
 */
@Embeddable
public class SchemaLogId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 932627987194023574L;
	private int structureId;
	private int userId;

	public SchemaLogId() {
	}

	public SchemaLogId(int structureId, int userId) {
		this.structureId = structureId;
		this.userId = userId;
	}

	@Column(name = "Structure_ID", nullable = false)
	public int getStructureId() {
		return this.structureId;
	}

	public void setStructureId(int structureId) {
		this.structureId = structureId;
	}

	@Column(name = "User_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaLogId))
			return false;
		SchemaLogId castOther = (SchemaLogId) other;

		return (this.getStructureId() == castOther.getStructureId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStructureId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
